/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/': RouteRecordInfo<
      '/guide/',
      '/guide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/effects': RouteRecordInfo<
      '/guide/effects',
      '/guide/effects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/fetching': RouteRecordInfo<
      '/guide/fetching',
      '/guide/fetching',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/input-and-context': RouteRecordInfo<
      '/guide/input-and-context',
      '/guide/input-and-context',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/keywords': RouteRecordInfo<
      '/guide/keywords',
      '/guide/keywords',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/testing': RouteRecordInfo<
      '/guide/testing',
      '/guide/testing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/your-first-script': RouteRecordInfo<
      '/guide/your-first-script',
      '/guide/your-first-script',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reference/': RouteRecordInfo<
      '/reference/',
      '/reference',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reference/files': RouteRecordInfo<
      '/reference/files',
      '/reference/files',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reference/imports': RouteRecordInfo<
      '/reference/imports',
      '/reference/imports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reference/limits': RouteRecordInfo<
      '/reference/limits',
      '/reference/limits',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reference/vocabulary': RouteRecordInfo<
      '/reference/vocabulary',
      '/reference/vocabulary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/404.vue': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/guide/index.md': {
      routes:
        | '/guide/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/guide/effects.md': {
      routes:
        | '/guide/effects'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/guide/fetching.md': {
      routes:
        | '/guide/fetching'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/guide/input-and-context.md': {
      routes:
        | '/guide/input-and-context'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/guide/keywords.md': {
      routes:
        | '/guide/keywords'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/guide/testing.md': {
      routes:
        | '/guide/testing'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/guide/your-first-script.md': {
      routes:
        | '/guide/your-first-script'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/reference/index.md': {
      routes:
        | '/reference/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/reference/files.md': {
      routes:
        | '/reference/files'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/reference/imports.md': {
      routes:
        | '/reference/imports'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/reference/limits.md': {
      routes:
        | '/reference/limits'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/reference/vocabulary.md': {
      routes:
        | '/reference/vocabulary'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
